services:

  ollama:
    image: ollama/ollama:0.1.38
    container_name: ollama
    hostname: ollama
    ports:
    - $OLLAMA__PORT:$OLLAMA__PORT
    volumes:
    - ollama:/root/.ollama
    tty: true
    restart: always
    networks:
    - datascience-network

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    hostname: open-webui
    env_file: .env
    environment:
      WEBUI_AUTH: $OPENWEBUI__WEBUI_AUTH
      OLLAMA_API_BASE_URL: $OPENWEBUI__OLLAMA_API_BASE_URL
    ports:
    - $OPENWEBUI__PORT:$OPENWEBUI__PORT
    volumes:
    - open-webui:/app/backend/data
    depends_on:
    - ollama
    extra_hosts:
    - host.docker.internal:host-gateway
    networks:
    - datascience-network

  jupyter:
    # image: quay.io/jupyter/pytorch-notebook:python-3.11
    # image: quay.io/jupyter/all-spark-notebook:python-3.11
    # image: quay.io/jupyter/tensorflow-notebook:python-3.11
    # image: quay.io/jupyter/pytorch-notebook:python-3.11
    image: quay.io/jupyter/datascience-notebook:python-3.11
    container_name: jupyter
    hostname: jupyter
    command: start-notebook.py --ServerApp.token=""
    tty: true
    env_file: .env
    environment:
      NB_GID: $JUPYTER__NB_GID
      NB_UID: $JUPYTER__NB_UID
      NB_NAME: $JUPYTER__NB_NAME
      GRANT_SUDO: $JUPYTER__GRANT_SUDO
      JUPYTER_PORT: $JUPYTER__PORT
      NOTEBOOK_ARGS: $JUPYTER__NOTEBOOK_ARGS
    volumes:
    - .:/app
    ports:
    - $JUPYTER__PORT:$JUPYTER__PORT
    networks:
    - jupyter-network

  app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    container_name: app
    hostname: app
    working_dir: /app
    user: vscode
    tty: true
    volumes:
    - .:/app
    networks:
    - jupyter-network
    - datascience-network

volumes:
  home:
  ollama:
  open-webui:

networks:
  datascience-network:
  jupyter-network:
